### PR TITLE
(feature) adds new dxw typeface

### PR DESCRIPTION
**Pull request by gazaston**
https://trello.com/c/CBIxH3VE/25-new-font-a-b-mock-ups

- replaces Founders Grotesk with Lato
- adds link to Lato on Google Fonts

### CODE REVIEW

**Comment by mec** [comment]
Be nice to pull both the weights so we get really good font rendering.

@import url('https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i');

If we don't use italics much we could let the browser do that:

@import url('https://fonts.googleapis.com/css?family=Lato:400,700');

Thoughts?

**Comment by gazaston** [comment]
Yes, have done exactly that on dxw.com locally (forgot to do it here!). Good spot.

**Comment by gazaston** [comment]
@mec I've updated the font import so we only pull in the two required weights.

**Comment by mec** [comment]
@gazaston looks good, shall we link in the BB to the Lato site? I used Lato on some client work and the site is often ahead of Google Fonts.

http://www.latofonts.com/

**Comment by gazaston** [comment]
It might be unnecessarily confusing — let's just keep the GF reference in there?

**Pull request merged**
