### PR TITLE
(feature) Now has a cover page

### PR DESCRIPTION
**Pull request by robbiepaul**
Uses the docsify cover page feature.

Docsify has some javascript that adds a random gradient to the background of the cover page so I've included an important css rule to override it.

screen shot 2017-12-14 at 13 21 11

### CODE REVIEW

**Comment by gazaston** [comment]
We should probably replace the current logo with Digital and Cyber versions?

**Review by gazaston — CHANGES_REQUESTED** [review]
We should probably replace the current logo with Digital and Cyber versions?

**Comment by robbiepaul** [comment]
@gazaston yep good shout, I'll update it

**Comment by robbiepaul** [comment]
Added, also rebased against master.

Ready for another look.

Screenshot:
screen shot 2017-12-18 at 13 53 51

**Pull request merged**
